# Generated by Django 4.1.6 on 2023-03-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_profile_about_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photos',
        ),
        migrations.AddField(
            model_name='profile',
            name='photos',
            field=models.ManyToManyField(blank=True, to='viewer.photo'),
        ),
    ]
