# Generated by Django 4.1.6 on 2023-02-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_link1',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_link2',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_link3',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_link4',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
