# Generated by Django 4.1.6 on 2023-04-01 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0005_status_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='status',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='status',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='status',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
