# Generated by Django 4.1.6 on 2023-06-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_profile_timeline_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='timeline_picture',
            new_name='cover_picture',
        ),
    ]
